In [2]:
from collections import Counter 

import pandas as pd
import numpy as np
import re

In [39]:
data_path = "data/"
df = pd.read_csv(data_path + "train.csv")

In [40]:
# df = df[:200]
df

,id,raw_address,POI/street
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika
1,1,"aye, jati sampurna",/
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung
3,3,"toko dita, kertosono",toko dita/
4,4,jl. orde baru,/jl. orde baru
...,...,...,...
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko
299997,299997,tanjung gusta jl. yaya 2 no 17,/
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/

In [41]:
len(df[df["POI/street"] == "/"])

31993

In [42]:
df["Empty"] = df["POI/street"].apply(lambda x : x == "/")
df = df[df["Empty"] == False]

In [43]:
df

,id,raw_address,POI/street,Empty
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika,False
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung,False
3,3,"toko dita, kertosono",toko dita/,False
4,4,jl. orde baru,/jl. orde baru,False
5,5,"raya samb gede, 299 toko bb kids",toko bb kids/raya samb gede,False
...,...,...,...,...
299994,299994,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,/kakap raya,False
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani,False
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko,False
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/,False
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/,False

In [44]:
def getPOI(s) :
    return s.split("/")[0]

def getStreet(s) :
    return s.split("/")[1]

def split(s) :
    return s.split(" ")

In [45]:
df["POI"] = df["POI/street"].apply(getPOI)
df["Street"] = df["POI/street"].apply(getStreet)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [46]:
df

,id,raw_address,POI/street,Empty,POI,Street
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika,False,,jl kapuk timur delta sili iii lippo cika
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung,False,,siung
3,3,"toko dita, kertosono",toko dita/,False,toko dita,
4,4,jl. orde baru,/jl. orde baru,False,,jl. orde baru
5,5,"raya samb gede, 299 toko bb kids",toko bb kids/raya samb gede,False,toko bb kids,raya samb gede
...,...,...,...,...,...,...
299994,299994,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,/kakap raya,False,,kakap raya
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani,False,,jend ahmad yani
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko,False,,raya cila kko
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/,False,taman asri,
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/,False,jaya maspion permata,

In [47]:
# Empty POI
len(df[df['POI'] == ''])

146516

In [48]:
# Empty Street
len(df[df['Street'] == ''])

38150

In [49]:
df["SplitStreet"] = df["Street"].apply(split)
df["SplitPOI"] = df["POI"].apply(split)
df["SplitRaw"] = df["raw_address"].apply(split)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [50]:
def f(words, sentence): 
    res = []
    for word in words :
        if sentence.find(word) == -1 :
            res.append(word)
    if len(res) == 0 :
        return False
    return res

In [51]:
df['TransformedPOI'] = df.apply(lambda x: f(x.SplitPOI, x.raw_address), axis=1)
df['TransformedStreet'] = df.apply(lambda x: f(x.SplitStreet, x.raw_address), axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [52]:
ndf = df[df["TransformedPOI"] == False]
ndf = ndf[ndf["TransformedStreet"] == False]
ndf

,id,raw_address,POI/street,Empty,POI,Street,SplitStreet,SplitPOI,SplitRaw,TransformedPOI,TransformedStreet
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika,False,,jl kapuk timur delta sili iii lippo cika,"[jl, kapuk, timur, delta, sili, iii, lippo, cika]",[],"[jl, kapuk, timur, delta, sili, iii, lippo, ci...",False,False
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung,False,,siung,[siung],[],"[setu, siung, 119, rt, 5, 1, 13880, cipayung]",False,False
3,3,"toko dita, kertosono",toko dita/,False,toko dita,,[],"[toko, dita]","[toko, dita,, kertosono]",False,False
4,4,jl. orde baru,/jl. orde baru,False,,jl. orde baru,"[jl., orde, baru]",[],"[jl., orde, baru]",False,False
5,5,"raya samb gede, 299 toko bb kids",toko bb kids/raya samb gede,False,toko bb kids,raya samb gede,"[raya, samb, gede]","[toko, bb, kids]","[raya, samb, gede,, 299, toko, bb, kids]",False,False
...,...,...,...,...,...,...,...,...,...,...,...
299994,299994,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,/kakap raya,False,,kakap raya,"[kakap, raya]",[],"[karawaci, baru, kakap, raya, 156, rt, 1, rw, ...",False,False
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani,False,,jend ahmad yani,"[jend, ahmad, yani]",[],"[jend, ahmad, yani, 331, kertasari, ciamis]",False,False
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko,False,,raya cila kko,"[raya, cila, kko]",[],"[raya, cila, kko,, cilandak, timur, kel.]",False,False
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/,False,taman asri,,[],"[taman, asri]","[jalan, cipadu, jaya, taman, asri, gang, bijak...",False,False
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/,False,jaya maspion permata,,[],"[jaya, maspion, permata]","[jaya, maspion, permata, blok, beryl, b2, , no...",False,False

In [53]:
# ndf = ndf.replace("", np.NaN)
cleandf = ndf.dropna()
cleandf = cleandf[["raw_address","POI", "Street"]]
cleandf

,raw_address,POI,Street
0,jl kapuk timur delta sili iii lippo cika 11 a ...,,jl kapuk timur delta sili iii lippo cika
2,setu siung 119 rt 5 1 13880 cipayung,,siung
3,"toko dita, kertosono",toko dita,
4,jl. orde baru,,jl. orde baru
5,"raya samb gede, 299 toko bb kids",toko bb kids,raya samb gede
...,...,...,...
299994,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,,kakap raya
299995,jend ahmad yani 331 kertasari ciamis,,jend ahmad yani
299996,"raya cila kko, cilandak timur kel.",,raya cila kko
299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri,
299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata,

In [54]:
def comma_preprocess(s) :
    s = s.replace("\t", " ")
    s = re.sub(r'([,/\\]+)', r' \1 ', s) # 
    s = re.sub(' +', ' ', s) # change multiple spaces into one space
    return s.strip()

s = "raya samb gede, 299 toko bb kids"
s = "jl. amd, komplek borneo lestari, blok 2, no. 30"
comma_preprocess(s)

'jl. amd , komplek borneo lestari , blok 2 , no. 30'

In [55]:
cleandf["Address"] = cleandf["raw_address"].apply(comma_preprocess)

In [56]:
cleandf

,raw_address,POI,Street,Address
0,jl kapuk timur delta sili iii lippo cika 11 a ...,,jl kapuk timur delta sili iii lippo cika,jl kapuk timur delta sili iii lippo cika 11 a ...
2,setu siung 119 rt 5 1 13880 cipayung,,siung,setu siung 119 rt 5 1 13880 cipayung
3,"toko dita, kertosono",toko dita,,"toko dita , kertosono"
4,jl. orde baru,,jl. orde baru,jl. orde baru
5,"raya samb gede, 299 toko bb kids",toko bb kids,raya samb gede,"raya samb gede , 299 toko bb kids"
...,...,...,...,...
299994,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,,kakap raya,karawaci baru kakap raya 156 rt 1 rw 3 karawaci
299995,jend ahmad yani 331 kertasari ciamis,,jend ahmad yani,jend ahmad yani 331 kertasari ciamis
299996,"raya cila kko, cilandak timur kel.",,raya cila kko,"raya cila kko , cilandak timur kel."
299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri,,jalan cipadu jaya taman asri gang bijaksana 3 ...
299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata,,jaya maspion permata blok beryl b2 no.58

In [57]:
def create_label(s, poi, street) :
    tokens = s.split(" ")
    n = len(tokens)
    tp = poi.split(" ")
    ts = street.split(" ")
    tags = []
    i = 0
    while i < n :
        if len(tp) > 0 and tokens[i] == tp[0] :
            j = 1
            while j < len(tp) :
                if i+j < n and tokens[i+j] == tp[j]:
                    j += 1
                else :
                    break
            if j == len(tp) :
                tags.append("B-ORGANISATION")
                for k in range(1, j) :
                    tags.append("I-ORGANISATION")
                i += j
            else :
                tags.append("O")
                i += 1
        elif len(ts) > 0 and tokens[i] == ts[0] :
            j = 1
            while j < len(ts) :
                if i+j < n and tokens[i+j] == ts[j] :
                    j += 1
                else :
                    break
            if j == len(ts) :
                tags.append("B-PLACE")
                for k in range(1, j) :
                    tags.append("I-PLACE")
                i += j
            else :
                tags.append("O")
                i += 1                
        else :
            tags.append("O")
            i += 1
        
#         print(tokens)
#         print(tags)

    if tokens[-1] != "." :
        tokens.append(".")
        tags.append("O")
    
    res = ""
#     print(tokens)
#     print(tags)
    for token, tag in zip(tokens, tags) :
        res += "{}\t{}\n".format(token, tag)
    return res

In [58]:
s = "raya samb gede , 299 toko bb kids"
poi = "toko bb kids"
street = "raya samb gede"
res = create_label(s, poi, street)
print(res)

raya	B-PLACE
samb	I-PLACE
gede	I-PLACE
,	O
299	O
toko	B-ORGANISATION
bb	I-ORGANISATION
kids	I-ORGANISATION
.	O

In [59]:
cleandf["Label"] = cleandf.apply(lambda x: create_label(x.Address, x.POI, x.Street), axis=1)

In [60]:
cleandf

,raw_address,POI,Street,Address,Label
0,jl kapuk timur delta sili iii lippo cika 11 a ...,,jl kapuk timur delta sili iii lippo cika,jl kapuk timur delta sili iii lippo cika 11 a ...,jl\tB-PLACE\nkapuk\tI-PLACE\ntimur\tI-PLACE\nd...
2,setu siung 119 rt 5 1 13880 cipayung,,siung,setu siung 119 rt 5 1 13880 cipayung,setu\tO\nsiung\tB-PLACE\n119\tO\nrt\tO\n5\tO\n...
3,"toko dita, kertosono",toko dita,,"toko dita , kertosono","toko\tB-ORGANISATION\ndita\tI-ORGANISATION\n,\..."
4,jl. orde baru,,jl. orde baru,jl. orde baru,jl.\tB-PLACE\norde\tI-PLACE\nbaru\tI-PLACE\n.\...
5,"raya samb gede, 299 toko bb kids",toko bb kids,raya samb gede,"raya samb gede , 299 toko bb kids","raya\tB-PLACE\nsamb\tI-PLACE\ngede\tI-PLACE\n,..."
...,...,...,...,...,...
299994,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,,kakap raya,karawaci baru kakap raya 156 rt 1 rw 3 karawaci,karawaci\tO\nbaru\tO\nkakap\tB-PLACE\nraya\tI-...
299995,jend ahmad yani 331 kertasari ciamis,,jend ahmad yani,jend ahmad yani 331 kertasari ciamis,jend\tB-PLACE\nahmad\tI-PLACE\nyani\tI-PLACE\n...
299996,"raya cila kko, cilandak timur kel.",,raya cila kko,"raya cila kko , cilandak timur kel.","raya\tB-PLACE\ncila\tI-PLACE\nkko\tI-PLACE\n,\..."
299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri,,jalan cipadu jaya taman asri gang bijaksana 3 ...,jalan\tO\ncipadu\tO\njaya\tO\ntaman\tB-ORGANIS...
299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata,,jaya maspion permata blok beryl b2 no.58,jaya\tB-ORGANISATION\nmaspion\tI-ORGANISATION\...

In [61]:
final = cleandf.sample(frac=1, random_state=0).reset_index(drop=True)
final

,raw_address,POI,Street,Address,Label
0,gg. sem 7 gombong gombong,,gg. sem 7,gg. sem 7 gombong gombong,gg.\tB-PLACE\nsem\tI-PLACE\n7\tI-PLACE\ngombon...
1,raya kebay lama cipulir kebayoran lama,,raya kebay lama,raya kebay lama cipulir kebayoran lama,raya\tB-PLACE\nkebay\tI-PLACE\nlama\tI-PLACE\n...
2,cik rt 2 8 tegal gundil,,cik,cik rt 2 8 tegal gundil,cik\tB-PLACE\nrt\tO\n2\tO\n8\tO\ntegal\tO\ngun...
3,beba jeruk indah ii sukagalih sukajadi,,beba jeruk indah ii,beba jeruk indah ii sukagalih sukajadi,beba\tB-PLACE\njeruk\tI-PLACE\nindah\tI-PLACE\...
4,"cipocok jaya jl. bha grand ser asri, no 15 421...",,jl. bha grand ser asri,"cipocok jaya jl. bha grand ser asri , no 15 42...",cipocok\tO\njaya\tO\njl.\tB-PLACE\nbha\tI-PLAC...
...,...,...,...,...,...
210869,"lindawati, a yani sen bis b 11",lindawati,a yani sen bis,"lindawati , a yani sen bis b 11","lindawati\tB-ORGANISATION\n,\tO\na\tB-PLACE\ny..."
210870,"pt. gemilang maju texindotama, jl. gatot subroto",pt. gemilang maju texindotama,jl. gatot subroto,"pt. gemilang maju texindotama , jl. gatot subroto",pt.\tB-ORGANISATION\ngemilang\tI-ORGANISATION\...
210871,"bonsai binor paiton raya pai,",bonsai binor paiton,raya pai,"bonsai binor paiton raya pai ,",bonsai\tB-ORGANISATION\nbinor\tI-ORGANISATION\...
210872,"kedai sumur gan, raya bukit cin gandul cinere",kedai sumur gandul,raya bukit cin,"kedai sumur gan , raya bukit cin gandul cinere","kedai\tO\nsumur\tO\ngan\tO\n,\tO\nraya\tB-PLAC..."
210873,"jln hadiah utama iiib, kavling polri blok e4 n...",kavling polri,jln hadiah utama,"jln hadiah utama iiib , kavling polri blok e4 ...",jln\tB-PLACE\nhadiah\tI-PLACE\nutama\tI-PLACE\...

In [62]:
n = len(final)
nt = int(0.95 * n)
train = final[:nt+1]
test = final[nt:]

In [63]:
train

,raw_address,POI,Street,Address,Label
0,gg. sem 7 gombong gombong,,gg. sem 7,gg. sem 7 gombong gombong,gg.\tB-PLACE\nsem\tI-PLACE\n7\tI-PLACE\ngombon...
1,raya kebay lama cipulir kebayoran lama,,raya kebay lama,raya kebay lama cipulir kebayoran lama,raya\tB-PLACE\nkebay\tI-PLACE\nlama\tI-PLACE\n...
2,cik rt 2 8 tegal gundil,,cik,cik rt 2 8 tegal gundil,cik\tB-PLACE\nrt\tO\n2\tO\n8\tO\ntegal\tO\ngun...
3,beba jeruk indah ii sukagalih sukajadi,,beba jeruk indah ii,beba jeruk indah ii sukagalih sukajadi,beba\tB-PLACE\njeruk\tI-PLACE\nindah\tI-PLACE\...
4,"cipocok jaya jl. bha grand ser asri, no 15 421...",,jl. bha grand ser asri,"cipocok jaya jl. bha grand ser asri , no 15 42...",cipocok\tO\njaya\tO\njl.\tB-PLACE\nbha\tI-PLAC...
...,...,...,...,...,...
200326,komplek abadi jln. amartha no:16,komplek abadi,jln. amartha,komplek abadi jln. amartha no:16,komplek\tB-ORGANISATION\nabadi\tI-ORGANISATION...
200327,cengkareng barat cen iv 67 rt 7 7 11730 cengka...,,cen iv,cengkareng barat cen iv 67 rt 7 7 11730 cengka...,cengkareng\tO\nbarat\tO\ncen\tB-PLACE\niv\tI-P...
200328,"bar jaya xiv, baratajaya gubeng",,bar jaya xiv,"bar jaya xiv , baratajaya gubeng","bar\tB-PLACE\njaya\tI-PLACE\nxiv\tI-PLACE\n,\t..."
200329,grand wisata cluster water garden blok bh.8 no...,water garden,,grand wisata cluster water garden blok bh.8 no...,grand\tO\nwisata\tO\ncluster\tO\nwater\tB-ORGA...
200330,nasi iii 278 sumberjaya cihaurbeuti,,nasi iii,nasi iii 278 sumberjaya cihaurbeuti,nasi\tB-PLACE\niii\tI-PLACE\n278\tO\nsumberjay...

In [64]:
def save_file(filename, arr) :
    f = open(filename, "w+",  encoding='utf-8')
    for s in arr :
        f.write(s.encode("ascii", "ignore").decode())
        f.write("\n")
    f.close()

In [65]:
train_path = data_path + "bert-fine-tune/train.txt"
validation_path = data_path + "bert-fine-tune/validation.txt"

train_data = train["Label"].values.tolist()
test_data = test["Label"].values.tolist()


ntry = None
# ntry = 1000
if ntry :
    train_data = train_data[:ntry]
    test_data = test_data[:ntry]

save_file(train_path, train_data)
save_file(validation_path, test_data)