In [1]:
from collections import Counter 

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
# df = df[:200]
df

,id,raw_address,POI/street
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika
1,1,"aye, jati sampurna",/
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung
3,3,"toko dita, kertosono",toko dita/
4,4,jl. orde baru,/jl. orde baru
...,...,...,...
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko
299997,299997,tanjung gusta jl. yaya 2 no 17,/
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/

In [4]:
len(df[df["POI/street"] == "/"])

31993

In [5]:
def getPOI(s) :
    return s.split("/")[0]

def getStreet(s) :
    return s.split("/")[1]

def split(s) :
    return s.split(" ")

In [8]:
df["POI"] = df["POI/street"].apply(getPOI)
df["Street"] = df["POI/street"].apply(getStreet)

In [9]:
df

,id,raw_address,POI/street,POI,Street
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika,,jl kapuk timur delta sili iii lippo cika
1,1,"aye, jati sampurna",/,,
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung,,siung
3,3,"toko dita, kertosono",toko dita/,toko dita,
4,4,jl. orde baru,/jl. orde baru,,jl. orde baru
...,...,...,...,...,...
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani,,jend ahmad yani
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko,,raya cila kko
299997,299997,tanjung gusta jl. yaya 2 no 17,/,,
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/,taman asri,
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/,jaya maspion permata,

In [10]:
# Empty POI
len(df[df['POI'] == ''])

178509

In [11]:
# Empty Street
len(df[df['Street'] == ''])

70143

In [10]:
df["SplitStreet"] = df["Street"].apply(split)
df["SplitPOI"] = df["POI"].apply(split)
df["SplitRaw"] = df["raw_address"].apply(split)

In [11]:
def f(words, sentence): 
    res = []
    for word in words :
        if sentence.find(word) == -1 :
            res.append(word)
    if len(res) == 0 :
        return False
    return res

In [12]:
df['TransformedPOI'] = df.apply(lambda x: f(x.SplitPOI, x.raw_address), axis=1)
df['TransformedStreet'] = df.apply(lambda x: f(x.SplitStreet, x.raw_address), axis=1)

In [13]:
df[df["TransformedPOI"] != False]

,id,raw_address,POI/street,POI,Street,SplitStreet,SplitPOI,SplitRaw,TransformedPOI,TransformedStreet
10,10,"cikahuripan sd neg boj 02 klap boj, no 5 16877",sd negeri bojong 02/klap boj,sd negeri bojong 02,klap boj,"[klap, boj]","[sd, negeri, bojong, 02]","[cikahuripan, sd, neg, boj, 02, klap, boj,, no...","[negeri, bojong]",False
11,11,"yaya atohar,",yayasan atohariyah/,yayasan atohariyah,,[],"[yayasan, atohariyah]","[yaya, atohar,]","[yayasan, atohariyah]",False
20,20,"toko bang ajs,",toko bangunan ajs/,toko bangunan ajs,,[],"[toko, bangunan, ajs]","[toko, bang, ajs,]",[bangunan],False
40,40,mar tabl metro iringmulyo metro timur,markaz tabligh metro/,markaz tabligh metro,,[],"[markaz, tabligh, metro]","[mar, tabl, metro, iringmulyo, metro, timur]","[markaz, tabligh]",False
44,44,sd neg 12 anggrek,sd negeri 12 anggrek/,sd negeri 12 anggrek,,[],"[sd, negeri, 12, anggrek]","[sd, neg, 12, anggrek]",[negeri],False
...,...,...,...,...,...,...,...,...,...,...
299963,299963,masl letjen sut,maslikah/letjen sut,maslikah,letjen sut,"[letjen, sut]",[maslikah],"[masl, letjen, sut]",[maslikah],False
299968,299968,"vok toko, k h mas mans, kampung bali",vokals toko/k h mas mans,vokals toko,k h mas mans,"[k, h, mas, mans]","[vokals, toko]","[vok, toko,, k, h, mas, mans,, kampung, bali]",[vokals],False
299974,299974,"islamic training cen pare, brawi, pelem pare",islamic training center pare/brawi,islamic training center pare,brawi,[brawi],"[islamic, training, center, pare]","[islamic, training, cen, pare,, brawi,, pelem,...",[center],False
299983,299983,"la banda minima, cile raya, pesanggrahan",la banda minimarket/cile raya,la banda minimarket,cile raya,"[cile, raya]","[la, banda, minimarket]","[la, banda, minima,, cile, raya,, pesanggrahan]",[minimarket],False
299990,299990,"ver, durian bajenis",veruna/,veruna,,[],[veruna],"[ver,, durian, bajenis]",[veruna],False

In [14]:
transform_poi = {}
for transformed, address  in zip(df["TransformedPOI"], df["SplitRaw"]) :
    if transformed :
        for t in transformed :
            for a in address :
                if a == t[:len(a)] :
                    transform_poi[a] = t
                    break

len(transform_poi)

8098

In [15]:
df[df["TransformedStreet"] != False]

,id,raw_address,POI/street,POI,Street,SplitStreet,SplitPOI,SplitRaw,TransformedPOI,TransformedStreet
69,69,cak 11 nagasari karawang barat,/cakrad,,cakrad,[cakrad],[],"[cak, 11, nagasari, karawang, barat]",False,[cakrad]
86,86,simpang tiga kah nasu no 112 28284 bukit raya,/kaharu nasu,,kaharu nasu,"[kaharu, nasu]",[],"[simpang, tiga, kah, nasu, no, 112, 28284, buk...",False,[kaharu]
117,117,ahmad dah iv kukusan beji,/ahmad dahlan iv,,ahmad dahlan iv,"[ahmad, dahlan, iv]",[],"[ahmad, dah, iv, kukusan, beji]",False,[dahlan]
130,130,mangla rege no h1 3 cimekar kel. cileunyi,/manglayang rege,,manglayang rege,"[manglayang, rege]",[],"[mangla, rege, no, h1, 3, cimekar, kel., cileu...",False,[manglayang]
184,184,"pasi redjeki, man kerto v, mojo",pasifik redjeki/man kertoarjo v,pasifik redjeki,man kertoarjo v,"[man, kertoarjo, v]","[pasifik, redjeki]","[pasi, redjeki,, man, kerto, v,, mojo]",[pasifik],[kertoarjo]
...,...,...,...,...,...,...,...,...,...,...
299862,299862,f. l tob 91 batang beruh sidikalang,/f. l tobing,,f. l tobing,"[f., l, tobing]",[],"[f., l, tob, 91, batang, beruh, sidikalang]",False,[tobing]
299870,299870,"wanasari kel. cemp viii, no 12",/cempaka viii,,cempaka viii,"[cempaka, viii]",[],"[wanasari, kel., cemp, viii,, no, 12]",False,[cempaka]
299910,299910,"kamp lio,",/kampung lio,,kampung lio,"[kampung, lio]",[],"[kamp, lio,]",False,[kampung]
299973,299973,moha toha no 167,/mohammad toha,,mohammad toha,"[mohammad, toha]",[],"[moha, toha, no, 167]",False,[mohammad]
299986,299986,"ginzi cafe, siliw,",ginzi cafe/siliwangi,ginzi cafe,siliwangi,[siliwangi],"[ginzi, cafe]","[ginzi, cafe,, siliw,]",False,[siliwangi]

In [16]:
transform_street = {}
for transformed, address  in zip(df["TransformedStreet"], df["SplitRaw"]) :
    if transformed :
        for t in transformed :
            for a in address :
                if a == t[:len(a)] :
                    transform_street[a] = t
                    break

len(transform_street)

2730

In [17]:
transform_poi["jl."]

'jl.rya'

In [18]:
transform_street["jl."]

'jl.ko.'

In [19]:
def preprocess(words) :
    res = []
    for word in words :
        if word in transform_poi :
            res.append(transform_poi[word])
        elif word in transform_street :
            res.append(transform_street[word])
        else :
            res.append(word)

    return " ".join(res) 
    
df["Raw"] = df["SplitRaw"].apply(preprocess)

In [20]:
df

,id,raw_address,POI/street,POI,Street,SplitStreet,SplitPOI,SplitRaw,TransformedPOI,TransformedStreet,Raw
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika,,jl kapuk timur delta sili iii lippo cika,"[jl, kapuk, timur, delta, sili, iii, lippo, cika]",[],"[jl, kapuk, timur, delta, sili, iii, lippo, ci...",False,False,"jl kapuk, timurraya deltasari silikon iii lipp..."
1,1,"aye, jati sampurna",/,,,[],[],"[aye,, jati, sampurna]",False,False,"aye, jatisari sampurna"
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung,,siung,[siung],[],"[setu, siung, 119, rt, 5, 1, 13880, cipayung]",False,False,setulus siung 119 rt 5 1 13880 cipayung
3,3,"toko dita, kertosono",toko dita/,toko dita,,[],"[toko, dita]","[toko, dita,, kertosono]",False,False,"toko dita, kertosono-kediri"
4,4,jl. orde baru,/jl. orde baru,,jl. orde baru,"[jl., orde, baru]",[],"[jl., orde, baru]",False,False,jl.rya orde baruna.
...,...,...,...,...,...,...,...,...,...,...,...
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani,,jend ahmad yani,"[jend, ahmad, yani]",[],"[jend, ahmad, yani, 331, kertasari, ciamis]",False,False,jendral ahmad yani 331 kertasari ciamis
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko,,raya cila kko,"[raya, cila, kko]",[],"[raya, cila, kko,, cilandak, timur, kel.]",False,False,"rayanka cilacap kko, cilandak timurraya kel."
299997,299997,tanjung gusta jl. yaya 2 no 17,/,,,[],[],"[tanjung, gusta, jl., yaya, 2, no, 17]",False,False,"tanjunganom, gusta jl.rya yayasan 2 notaris 17"
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/,taman asri,,[],"[taman, asri]","[jalan, cipadu, jaya, taman, asri, gang, bijak...",False,False,jalan cipadu jayalas tamansari asrigaha gangsa...
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/,jaya maspion permata,,[],"[jaya, maspion, permata]","[jaya, maspion, permata, blok, beryl, b2, , no...",False,False,jayalas maspion permata blokplan beryl b2 asra...